### ISSUE TITLE
Menú del programa

### ISSUE THREAD

**Issue by lquintanac** [aigora/twIE_2021-matpack#2]
Debéis generar código que implemente un **menú provisional** con el que el usuario de vuestro programa debe interactuar. Este menú debe contener las opciones necesarias para acceder a las funcionalidades previstas, aunque aún no realizará ninguna acción. 
El menú estará implementado mediante un bucle `switch-case` y se repetirá indefinidamente hasta que el usuario decida salir del programa.

**Comment by orgynmobs** [comment]
Habéis subido los fichero que tenéis además que cerrar la issue. Lo podeís hacer justo aquí abajo.

**Comment by orgynmobs** [comment]
Aún no habéis aplicado los cambio. Hacedlo cuando podáis y cerrad la milestone si está al 100%
